-- sys_role
CREATE TABLE sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(50)  NOT NULL,
    role_desc   VARCHAR(100),
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    deleted     SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uk_role_name ON sys_role (role_name) WHERE deleted = 0;

-- sys_permission
CREATE TABLE sys_permission (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name  VARCHAR(50)  NOT NULL,
    permission_desc  VARCHAR(100),
    resource_type    VARCHAR(20)  NOT NULL,
    resource_key     VARCHAR(100),
    parent_id        BIGINT       DEFAULT NULL,
    status           SMALLINT     NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uk_permission_name ON sys_permission (permission_name) WHERE deleted = 0;

-- sys_user
CREATE TABLE sys_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100) NOT NULL,
    nickname    VARCHAR(50),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    avatar      VARCHAR(255),
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    deleted     SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uk_user_username ON sys_user (username) WHERE deleted = 0;
CREATE UNIQUE INDEX uk_user_email ON sys_user (email) WHERE deleted = 0 AND email IS NOT NULL;
CREATE INDEX idx_user_status ON sys_user (status) WHERE deleted = 0;

-- sys_user_role (复合主键)
CREATE TABLE sys_user_role (
    user_id   BIGINT NOT NULL REFERENCES sys_user(id),
    role_id   BIGINT NOT NULL REFERENCES sys_role(id),
    PRIMARY KEY (user_id, role_id)
);

-- sys_role_permission (复合主键)
CREATE TABLE sys_role_permission (
    role_id       BIGINT NOT NULL REFERENCES sys_role(id),
    permission_id BIGINT NOT NULL REFERENCES sys_permission(id),
    PRIMARY KEY (role_id, permission_id)
);

-- 初始角色
INSERT INTO sys_role (role_name, role_desc) VALUES ('ADMIN', '系统管理员');
INSERT INTO sys_role (role_name, role_desc) VALUES ('USER', '普通用户');

-- 初始权限
INSERT INTO sys_permission (permission_name, permission_desc, resource_type, resource_key) VALUES
('chat:send',           '发送聊天消息', 'API', 'POST /api/chat'),
('chat:stream',         '流式聊天',     'API', 'GET /api/chat/stream'),
('conversation:manage', '管理对话记录', 'API', '*'),
('model:config',        '配置模型参数', 'API', '*'),
('prompt:manage',       '管理系统提示词','API', '*'),
('usage:view',          '查看用量统计', 'API', '*'),
('user:manage',         '管理用户',     'API', '*'),
('role:manage',         '管理角色权限', 'API', '*');

-- ADMIN 拥有全部权限
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 1, id FROM sys_permission;

-- USER 拥有基础权限
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 2, id FROM sys_permission
WHERE permission_name IN ('chat:send', 'chat:stream', 'conversation:manage', 'usage:view');

-- 初始管理员 (密码: admin123 的 BCrypt hash)
INSERT INTO sys_user (username, password, nickname, status) VALUES
('admin', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Kz2u0bF/8bF4W2vF4I0Gq', '系统管理员', 1);
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
