-- V23__outbox.sql — publisher outbox 表（OutboxMessageBus / OutboxRelay）
-- 跨 child 契约（08-05-publisher-reliability-outbox）：V10–V22 已占用，本任务用 V23。
-- 幂等：CREATE TABLE / INDEX IF NOT EXISTS，可重复执行。
CREATE TABLE IF NOT EXISTS outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic          VARCHAR(128)  NOT NULL,                    -- 裸 topic 名（无前缀）
    payload        JSONB         NOT NULL,                    -- codec.encode(payload) 的 JSON 文本
    payload_type   VARCHAR(255)  NOT NULL,                    -- payload.getClass().getName()，relay 反序列化用（评审 P1-4）
    tag            VARCHAR(255),                              -- MessageEnvelope.tag（评审 P1-8，当前三 publisher 不用，可空）
    dedup_key      VARCHAR(255),                              -- 幂等键（消费端 SETNX，可空）
    hash_key       VARCHAR(255),                              -- 有序分区键（rag_index_document 用 documentId，可空）
    headers        JSONB         NOT NULL DEFAULT '{}',       -- 含 publisher 的 traceparent/Content-Type 等
    status         VARCHAR(16)   NOT NULL DEFAULT 'pending',  -- pending / claiming / dead
    attempts       INT           NOT NULL DEFAULT 0,          -- 仅统计"对看似可达 MQ 的真实投递尝试"（评审 P1-7）
    next_retry_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    failure_reason TEXT,                                      -- dead 时的异常摘要
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()       -- claiming 超时回收依据；claim 时刷新
);
-- relay 扫描热路径（pending/claiming，claiming 超时回收）
CREATE INDEX IF NOT EXISTS idx_outbox_claim ON outbox (status, next_retry_at, created_at)
    WHERE status IN ('pending', 'claiming');
-- dead 清理任务的部分索引（评审"性能"P3，避免 dead 行全表扫）
CREATE INDEX IF NOT EXISTS idx_outbox_dead_cleanup ON outbox (status, created_at)
    WHERE status = 'dead';
