-- 用量统计模块重写（08-17-usage-rework）
-- token_usage 退役：无 user_id 列（隔离靠 conversation 前缀 LIKE）、token 未知用 -1 哨兵、
-- 无法支撑时间桶/总计/管理员维度查询。无存量用户，直接重建为 usage_event：
--   * 显式 user_id 维度（管理员可查他人）
--   * scene 场景维度（CHAT/AGENT/INTENT）
--   * event_id 唯一约束（消费幂等兜底，替代会碰撞的 conversationId:candidateId:毫秒桶键）
--   * token 列 NULL 表未知（SUM 自然忽略），estimated 标记字符估算值

DROP TABLE IF EXISTS token_usage;

CREATE TABLE IF NOT EXISTS usage_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          UUID        NOT NULL,
    user_id           BIGINT      NOT NULL,
    scene             VARCHAR(32) NOT NULL,
    conversation_id   VARCHAR(64),
    model_id          VARCHAR(64) NOT NULL,
    prompt_tokens     BIGINT,
    completion_tokens BIGINT,
    total_tokens      BIGINT,
    estimated         BOOLEAN     NOT NULL DEFAULT FALSE,
    success           BOOLEAN     NOT NULL,
    duration_ms       BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_usage_event_event_id ON usage_event (event_id);
CREATE INDEX IF NOT EXISTS idx_usage_event_user_time ON usage_event (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_usage_event_time ON usage_event (created_at);
CREATE INDEX IF NOT EXISTS idx_usage_event_model ON usage_event (model_id);

-- 权限：usage:view:all 查看全部用户用量（循 V22 先例：整权限仅绑 ADMIN；usage:view 仍为 USER 可见的本人维度）
INSERT INTO sys_permission (permission_name, permission_desc, resource_type, resource_key)
SELECT 'usage:view:all', '查看全部用户用量统计', 'API', '*'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE permission_name = 'usage:view:all');

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_permission p
WHERE r.role_name = 'ADMIN'
  AND p.permission_name = 'usage:view:all'
  AND NOT EXISTS (
    SELECT 1 FROM sys_role_permission rp
    WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
