-- system_prompt (从 JPA Entity 迁移)
CREATE TABLE IF NOT EXISTS system_prompt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id    VARCHAR(100) NOT NULL,
    prompt_text TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_system_prompt_model ON system_prompt (model_id);

-- model_params (从 JPA Entity 迁移)
CREATE TABLE IF NOT EXISTS model_params (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id      VARCHAR(100) NOT NULL,
    param_key     VARCHAR(100) NOT NULL,
    param_value   VARCHAR(500) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_model_params_key ON model_params (model_id, param_key);

-- token_usage (从 JPA Entity 迁移)
CREATE TABLE IF NOT EXISTS token_usage (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   VARCHAR(100),
    model_id          VARCHAR(100),
    prompt_tokens     BIGINT       DEFAULT 0,
    completion_tokens BIGINT       DEFAULT 0,
    total_tokens      BIGINT       DEFAULT 0,
    duration_ms       BIGINT       DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_usage_conversation ON token_usage (conversation_id);
CREATE INDEX IF NOT EXISTS idx_usage_model ON token_usage (model_id);
CREATE INDEX IF NOT EXISTS idx_usage_created ON token_usage (created_at);
