-- V32__document_image.sql — PDF 图片提取清单表（design §6.3，pdf-image-extraction.md）
-- 前台管线编号一次并持久化；后台消费者按 PENDING 行逐条提取上传 MinIO。
-- 幂等：CREATE TABLE / INDEX IF NOT EXISTS，可重复执行。
CREATE TABLE IF NOT EXISTS document_image (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT        NOT NULL,
    page_number     INT           NOT NULL,                    -- 0-based
    seq             INT           NOT NULL,                    -- 文档内连续序号
    img_type        VARCHAR(16)   NOT NULL,                    -- XOBJECT | PAGE_RENDER
    bbox            JSONB         NOT NULL,                    -- [l,b,r,t]
    object_num      INT,                                        -- XOBJECT: ObjectKey.number
    object_gen      INT,                                        -- XOBJECT: ObjectKey.generation
    x_object_name   VARCHAR(255),                              -- XOBJECT: 资源名（诊断用）
    storage_key     VARCHAR(512)  NOT NULL,                    -- images/{documentId}/p{page+1}-{seq}.{ext}
    producer_version VARCHAR(64)  NOT NULL,                    -- 前台生成 manifest 时的 ODL 版本戳（P3 对账 version_skew）
    status          VARCHAR(16)   NOT NULL DEFAULT 'PENDING',  -- PENDING|UPLOADED|FAILED|SKIPPED
    fail_reason     VARCHAR(512),
    file_size       BIGINT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (document_id, seq)
);
-- 消费侧 findPending + 状态维度聚合
CREATE INDEX IF NOT EXISTS idx_document_image_doc ON document_image (document_id, status);
-- 超龄 PENDING 告警 / P3 补偿扫描
CREATE INDEX IF NOT EXISTS idx_document_image_pending_age ON document_image (status, created_at)
    WHERE status = 'PENDING';
