-- V4: Spring AI Chat Memory table + index
-- Take over schema ownership from Spring AI's initialize-schema
-- This is the single source of truth for the table structure

CREATE TABLE IF NOT EXISTS spring_ai_chat_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_memory_conv_created
    ON spring_ai_chat_memory (conversation_id, created_at DESC);
