-- ============================================================
-- V9__add_team.sql — 团队协作功能
-- ============================================================

-- ==================== 团队表 ====================

CREATE TABLE IF NOT EXISTS team (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name       VARCHAR(128) NOT NULL,
    team_desc       VARCHAR(512),
    creator_id      BIGINT       NOT NULL REFERENCES sys_user(id),
    default_upload_limit_mb  BIGINT NOT NULL DEFAULT 50,
    creator_upload_limit_mb  BIGINT NOT NULL DEFAULT 200,
    status          SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted         SMALLINT     NOT NULL DEFAULT 0
);

-- 团队名称唯一（未删除的）
CREATE UNIQUE INDEX IF NOT EXISTS uk_team_name_active ON team (team_name) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_team_creator ON team (creator_id);

COMMENT ON TABLE team IS '团队表';
COMMENT ON COLUMN team.status IS '1=启用 0=禁用';
COMMENT ON COLUMN team.deleted IS '逻辑删除 0=正常 1=已删除';

-- ==================== 团队成员表 ====================

CREATE TABLE IF NOT EXISTS team_member (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id          BIGINT       NOT NULL REFERENCES team(id),
    user_id          BIGINT       NOT NULL REFERENCES sys_user(id),
    role             SMALLINT     NOT NULL DEFAULT 10,
    upload_limit_mb  BIGINT       NOT NULL DEFAULT 50,
    status           SMALLINT     NOT NULL DEFAULT 1,
    joined_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 活跃成员唯一（同一团队同一用户只允许一条 status=1 记录）
CREATE UNIQUE INDEX IF NOT EXISTS uk_team_user_active ON team_member (team_id, user_id) WHERE status = 1;
CREATE INDEX IF NOT EXISTS idx_team_member_user ON team_member (user_id, status);

COMMENT ON TABLE team_member IS '团队成员表';
COMMENT ON COLUMN team_member.role IS '10=MEMBER 20=ADMIN 30=CREATOR';
COMMENT ON COLUMN team_member.status IS '1=正常 0=已移除（不用 @TableLogic，同一用户可重新加入）';

-- ==================== 团队上传审批表 ====================

CREATE TABLE IF NOT EXISTS team_upload_approval (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id         BIGINT       NOT NULL REFERENCES team(id),
    document_id     BIGINT       NOT NULL REFERENCES rag_document(id),
    uploader_id     BIGINT       NOT NULL REFERENCES sys_user(id),
    status          SMALLINT     NOT NULL DEFAULT 0,
    reviewer_id     BIGINT       REFERENCES sys_user(id),
    review_comment  VARCHAR(512),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    reviewed_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_approval_team_status ON team_upload_approval (team_id, status);
CREATE INDEX IF NOT EXISTS idx_approval_uploader ON team_upload_approval (uploader_id);

COMMENT ON TABLE team_upload_approval IS '团队上传审批表';
COMMENT ON COLUMN team_upload_approval.status IS '0=PENDING 1=APPROVED 2=REJECTED';

-- ==================== rag_document 加 team_id ====================

ALTER TABLE rag_document ADD COLUMN IF NOT EXISTS team_id BIGINT DEFAULT NULL;
COMMENT ON COLUMN rag_document.team_id IS '所属团队 ID（NULL=个人文档）';

CREATE INDEX IF NOT EXISTS idx_rag_document_team ON rag_document (team_id);

-- ==================== 清空现有向量数据（开发阶段） ====================

-- WARNING: 开发阶段专用，生产环境需删除此行
TRUNCATE TABLE vector_store;

-- ==================== 新增团队权限 ====================

INSERT INTO sys_permission (permission_name, permission_desc, resource_type, resource_key)
SELECT '团队查看', '查看团队信息', 'MENU', 'team:view'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE resource_key = 'team:view');

INSERT INTO sys_permission (permission_name, permission_desc, resource_type, resource_key)
SELECT '团队管理', '管理团队（设置额度等）', 'MENU', 'team:manage'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE resource_key = 'team:manage');

-- 绑定 team:manage 到 ADMIN 角色
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r, sys_permission p
WHERE r.role_name = 'ADMIN' AND p.resource_key = 'team:manage'
  AND NOT EXISTS (
    SELECT 1 FROM sys_role_permission rp
    WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
