-- ============================================================
-- chat-demo 全量建表脚本
-- 用法: 首次部署时手动执行一次（psql -f schema.sql）
-- 兼容 PostgreSQL 15+（推荐 bookworm 镜像）
-- ============================================================

-- ========== 用户权限模块 ==========

-- sys_role
CREATE TABLE IF NOT EXISTS sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(50)  NOT NULL,
    role_desc   VARCHAR(100),
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    deleted     SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_name ON sys_role (role_name) WHERE deleted = 0;

-- sys_permission
CREATE TABLE IF NOT EXISTS sys_permission (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name  VARCHAR(50)  NOT NULL,
    permission_desc  VARCHAR(100),
    resource_type    VARCHAR(20)  NOT NULL,
    resource_key     VARCHAR(100),
    parent_id        BIGINT       DEFAULT NULL,
    status           SMALLINT     NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_permission_name ON sys_permission (permission_name) WHERE deleted = 0;

-- sys_user（id 由雪花算法生成，不使用数据库自增）
CREATE TABLE IF NOT EXISTS sys_user (
    id          BIGINT PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100) NOT NULL,
    nickname    VARCHAR(50),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    avatar      VARCHAR(255),
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    deleted     SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username ON sys_user (username) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_email ON sys_user (email) WHERE deleted = 0 AND email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_status ON sys_user (status) WHERE deleted = 0;

-- sys_user_role（联合主键，无自增 id）
CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id   BIGINT NOT NULL REFERENCES sys_user(id),
    role_id   BIGINT NOT NULL REFERENCES sys_role(id),
    PRIMARY KEY (user_id, role_id)
);

-- sys_role_permission（联合主键，无自增 id）
CREATE TABLE IF NOT EXISTS sys_role_permission (
    role_id       BIGINT NOT NULL REFERENCES sys_role(id),
    permission_id BIGINT NOT NULL REFERENCES sys_permission(id),
    PRIMARY KEY (role_id, permission_id)
);

-- ========== 业务模块 ==========

-- system_prompt
CREATE TABLE IF NOT EXISTS system_prompt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id    VARCHAR(100) NOT NULL,
    prompt_text TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_system_prompt_model ON system_prompt (model_id);

-- model_params（模型参数配置，每个模型一行）
CREATE TABLE IF NOT EXISTS model_params (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id            VARCHAR(100) NOT NULL,
    temperature         DOUBLE PRECISION,
    max_tokens          INTEGER,
    top_p               DOUBLE PRECISION,
    frequency_penalty   DOUBLE PRECISION,
    presence_penalty    DOUBLE PRECISION,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_model_params_model ON model_params (model_id);

-- token_usage
CREATE TABLE IF NOT EXISTS token_usage (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   VARCHAR(100),
    model_id          VARCHAR(100),
    prompt_tokens     BIGINT       DEFAULT 0,
    completion_tokens BIGINT       DEFAULT 0,
    total_tokens      BIGINT       DEFAULT 0,
    duration_ms       BIGINT       DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_usage_conversation ON token_usage (conversation_id);
CREATE INDEX IF NOT EXISTS idx_usage_model ON token_usage (model_id);
CREATE INDEX IF NOT EXISTS idx_usage_created ON token_usage (created_at);

-- ========== Spring AI Chat Memory ==========

CREATE TABLE IF NOT EXISTS spring_ai_chat_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_memory_conv_created
    ON spring_ai_chat_memory (conversation_id, created_at DESC);

-- ========== 初始数据 ==========

-- 初始角色（仅在表为空时插入）
INSERT INTO sys_role (role_name, role_desc)
SELECT 'ADMIN', '系统管理员' WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE role_name = 'ADMIN');
INSERT INTO sys_role (role_name, role_desc)
SELECT 'USER', '普通用户' WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE role_name = 'USER');

-- 初始权限
INSERT INTO sys_permission (permission_name, permission_desc, resource_type, resource_key)
SELECT p.permission_name, p.permission_desc, p.resource_type, p.resource_key
FROM (VALUES
    ('chat:send',           '发送聊天消息', 'API', 'POST /api/chat'),
    ('chat:stream',         '流式聊天',     'API', 'GET /api/chat/stream'),
    ('conversation:manage', '管理对话记录', 'API', '*'),
    ('model:config',        '配置模型参数', 'API', '*'),
    ('prompt:manage',       '管理系统提示词','API', '*'),
    ('usage:view',          '查看用量统计', 'API', '*'),
    ('user:manage',         '管理用户',     'API', '*'),
    ('role:manage',         '管理角色权限', 'API', '*')
) AS p(permission_name, permission_desc, resource_type, resource_key)
WHERE NOT EXISTS (
    SELECT 1 FROM sys_permission WHERE permission_name = p.permission_name
);

-- ADMIN 拥有全部权限
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r, sys_permission p
WHERE r.role_name = 'ADMIN'
  AND NOT EXISTS (SELECT 1 FROM sys_role_permission WHERE role_id = r.id AND permission_id = p.id);

-- USER 拥有基础权限
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r, sys_permission p
WHERE r.role_name = 'USER' AND p.permission_name IN ('chat:send', 'chat:stream', 'conversation:manage', 'usage:view')
  AND NOT EXISTS (SELECT 1 FROM sys_role_permission WHERE role_id = r.id AND permission_id = p.id);

-- 初始管理员 (密码: admin123)
INSERT INTO sys_user (id, username, password, nickname, status)
SELECT 1, 'admin', '$2a$10$kK3Qf5iixQQ.De4smj0k9OE/7A.nxhHAe.6U2R11foJ5WIdup2q8.', '系统管理员', 1
WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE username = 'admin');

-- 绑定管理员角色
INSERT INTO sys_user_role (user_id, role_id)
SELECT u.id, r.id FROM sys_user u, sys_role r
WHERE u.username = 'admin' AND r.role_name = 'ADMIN'
  AND NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = u.id AND role_id = r.id);

-- ========== RAG 文档管理 ==========

-- RAG 文档管理表
CREATE TABLE IF NOT EXISTS rag_document (
    id          BIGSERIAL PRIMARY KEY,
    file_name   VARCHAR(500) NOT NULL,
    file_size   BIGINT       NOT NULL,
    mime_type   VARCHAR(200) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    bucket      VARCHAR(200) NOT NULL,
    chunk_count INTEGER      DEFAULT 0,
    status      VARCHAR(50)  NOT NULL DEFAULT 'UPLOADED',
    error_message TEXT,
    create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INTEGER       NOT NULL DEFAULT 0
);

COMMENT ON TABLE  rag_document IS 'RAG 文档管理';
COMMENT ON COLUMN rag_document.id IS '主键';
COMMENT ON COLUMN rag_document.file_name IS '原始文件名';
COMMENT ON COLUMN rag_document.file_size IS '文件大小(bytes)';
COMMENT ON COLUMN rag_document.mime_type IS 'MIME类型';
COMMENT ON COLUMN rag_document.storage_key IS 'MinIO存储key';
COMMENT ON COLUMN rag_document.bucket IS 'MinIO bucket';
COMMENT ON COLUMN rag_document.chunk_count IS '解析后分块数';
COMMENT ON COLUMN rag_document.status IS '处理状态: UPLOADED/PARSING/CHUNKING/COMPLETED/FAILED';
COMMENT ON COLUMN rag_document.error_message IS '错误信息';
COMMENT ON COLUMN rag_document.create_time IS '创建时间';
COMMENT ON COLUMN rag_document.update_time IS '更新时间';
COMMENT ON COLUMN rag_document.deleted IS '逻辑删除';
